name: Node.js/React Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
    - name: Use Node.js $
      uses: actions/setup-node@v3
      env:
        FORCE_COLOR: 0
      with:
        node-version: '14'
        architecture: 'x64'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy production artifacts
      run: |
        cp -r $GITHUB_WORKSPACE/build/* /var/www/prudinskaya.com
